spring:
  profiles:
    active: dev
  aop:
    proxy-target-class: true
  application:
    name: wshop-main
  devtools:
    restart:
      enabled: true
  datasource:
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/wshop
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:/db/xml/**/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
  global-config:
    db-config:
      id-type: auto

redis:
  host: 127.0.0.1:6379

wshop:
  service:
    version: 1.0.0

dubbo:
  registry:
    protocol: zookeeper
    timeout: 20000
    address: 127.0.0.1:2181
server:
  port: 8080

