spring:
  application:
    name: wshop-main
  devtools:
    restart:
      enabled: true
  datasource:
    username: root
    password: iruby234
    url: jdbc:mysql://121.4.73.4:3306/wshop
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:/db/xml/**/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
  global-config:
    db-config:
      id-type: auto

redis:
  host: 121.4.73.4:6379
  
wshop:
  service:
    version: 1.0.0

dubbo:
  registry:
    protocol: zookeeper
    timeout: 20000
    address: 121.4.73.4:2181

server:
  port: 8080