spring:
  application:
    name: wshop-main
  devtools:
    restart:
      enabled: true
  datasource:
    username: root
    password: iruby234
    url: jdbc:mysql://121.4.73.4:3306/wshop
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  mapper-locations: classpath*:/db/xml/**/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
  #    对所有的 resultMap 都进行自动映射
  #    autoMappingBehavior: FULL
  global-config:
    db-config:
      id-type: auto

#wshop:
#  service:
#    version: 1.0.0

zookeeper:
  port: 2181

dubbo:
  registry:
    address: zookeeper://121.4.73.4:${zookeeper.port}
